questions
MaKu-kodilla/portfolio-project pull request #1
Opened 2018-04-18 19:10 UTC by MaKu-kodilla

Hej Michał,

trochę się napracowałem przy tej strone, ale myślę, że było warto :)

Mam problem z nawigacją.
Masz jakiś pomysł jak mógłbym ją zaimplementować w mniejszych urządzeniach?

2018-05-04 16:41 UTC, michal-bootcamp requested changes
1. jak najezdzam na film z youtube’a, to caly ten film dziwnie skacze/przesuwa sie - zlikwiduj to zachowanie
2. od szerokosci ok 992px do ok 1200px obrazki w galerii nachodza na siebie
3. niech te zaokraglenia beda rowne/symetryczne: https://scr.hu/dP7BN6
4. na takim widoku: https://scr.hu/M7mXG2 fajnie by bylo, gdyby zawsze ten pin z mapy byl widoczny, a teksty przy ikonach kiedy linia lamana jest na dwie, to nie wpadaly pod ikone, ale zachowywaly odstep - polecam do tego flexboxa
5. na widoku mobilnym wysrodkuj prosze zdjecia: https://scr.hu/Lvm1v3
6. zeby pierwsza sekcja lepiej wygladala na telefonach, ustawilbym jej wysokosc na 100vh i dodal jakas min-height w pikselach https://scr.hu/Ozma9a
7. jak juz masz te strzalke `btn-back`, to mozesz dorobic tam “kotwice”, ktora bedzie linkiem, do sekcji/elementu gdzies na gorze strony
8. sprawdz zachowanie mobilnego menu pod Firefoxem (i jesli masz opcje pod Androidem)

2018-05-04 16:41 UTC, michal-bootcamp commented on sass/style.scss
> +        border-radius: 30%;
popraw ten border-radius tutaj oraz dla wszystkich buttonow, zeby zaokraglenia wygladaly rowno, analogicznie jak na projekcie

2018-05-04 16:41 UTC, michal-bootcamp commented on sass/style.scss
> +    }
ostatnie 4 linie o jedno wciecie za duzo

2018-05-20 12:20 UTC, MaKu-kodilla commented on sass/style.scss
> +        border-radius: 30%;
Ad. 4 
https://scr.hu/AwyRyO: teraz dwie górne ikonki wyglądają tak.
Masz jakiś pomysł? 
Jeśli chodzi o ten pin to musiałbym mieć background image widoczny w 100%, również nie mam pomysłu jak to ogarnąć.

Ad.3 Ustawiłem im jeden border radius. Jak mogę sprawić, żeby  były symetryczne w inny sposób?

Oprócz tego do zrobienia mam jeszcze pkt 2 oraz 8 :)

2018-05-23 14:57 UTC, michal-bootcamp commented
jesli chodzi o border-radius to nie musisz ustawiac go w procentach :)

jesli chodzi o background z mapka i tym pinem, to pokombinuj z `background-position` i wartosciami np w pikselach

te kotwice #home zamien z `name` na `id` i przenies ja do `<nav>` zeby ten link na logo nie stawal sie aktywny tak jak teraz

2018-05-28 02:06 UTC, michal-bootcamp commented
duzo lepiej :) popraw jeszcze prosze te border-radiusy w sekcji `projects` i w sekcji `price`

2018-05-28 23:36 UTC, merged